name: "MegaLinter Custom Flavor: Carbonara"
author: "pessi-v"
description: "MegaLinter Custom Flavor Carbonara"
outputs:
  has_updated_sources:
    description: "0 if no source file has been updated, 1 if source files has been updated"
runs:
  using: "docker"
  # You can manually update the Docker image version here, or use the latest tag
  image: "docker://ghcr.io/git@github.com:pessi-v/megalinter-custom-flavor-carbonara/megalinter-custom-flavor:latest"
  args:
    - "-v"
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
branding:
  icon: "check"
  color: "green"
